### ISSUE TITLE
Crash on Launch in iOS 13.1

### ISSUE THREAD

**Issue by n8henrie** [pulsely/PulseModemA#1]
I don't recall if it worked with iOS 13.0.

**Comment by pulsely** [comment]
Thanks a lot @n8henrie for your report. We are uploading a new build to the AppStore, that should fix the issue.

We didn't expect that it stops working on 13.1. Seem to work fine on 13.0.

**Comment by n8henrie** [comment]
Can confirm that crash-on-launch is fixed in the new app-store version.
