### ISSUE TITLE
Host name shows up in passcode field on my iPhone and iPad 

### ISSUE THREAD

**Issue by rodgerzeisler** [pulsely/PulseModemA#10]
![41CAC48B-2B0B-43C2-A0BE-7AFE73F544CC](https://user-images.githubusercontent.com/31865083/232166651-31cf72a0-f26f-4cd1-84f9-429deaaa1319.jpeg)

When I click the gear on the APRS Feed page, the APRS Host name shows up in the APRS Passcode field.  To enter the passcode, I click on the Host field and a numeric keypad pops up.  I enter the passcode. It accepts it and shows ….. in that field (screenshot didn’t capture the …. in Host) and shows the host in the passcode field. I then click Disconnected and all connects perfectly. Just a GUI issue.

**Comment by pulsely** [comment]
Thank you for your report. The issue has been fixed. New build is currently being submitted to the AppStore.
