### ISSUE TITLE
Changed Call Sign Issues

### ISSUE THREAD

**Issue by drgunter99** [pulsely/PulseModemA#9]
I changed my call sign and attempted to update Pulsemodem. I generated a new passcode for my new call sign but I cannot get it to go online now. I am having issues with entering the APRS host - the number keypad shows up there and periodically, the passcode is being copied to the APRS Host control. I’ve tried deleting, rebooting the phone, and reentering the setup data. I am running iOS 16.3.

**Comment by pulsely** [comment]
Thank you for your report. The behavior problem has been fixed. New build is currently under review at the AppStore and will be approved shortly. Thanks.
